/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ua_org_antidotcb_dominus_engine_NativeQuatUtils */

#ifndef _Included_ua_org_antidotcb_dominus_engine_NativeQuatUtils
#define _Included_ua_org_antidotcb_dominus_engine_NativeQuatUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ua_org_antidotcb_dominus_engine_NativeQuatUtils
 * Method:    normalizeQuaternion
 * Signature: (Lua/org/antidotcb/dominus/engine/Quaternion;)I
 */
JNIEXPORT jint JNICALL Java_ua_org_antidotcb_dominus_engine_NativeQuatUtils_normalizeQuaternion
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
