/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ua_org_antidotcb_dominus_engine_QuaternionNativeHelper_Quaternion */

#ifndef _Included_ua_org_antidotcb_dominus_engine_QuaternionNativeHelper_Quaternion
#define _Included_ua_org_antidotcb_dominus_engine_QuaternionNativeHelper_Quaternion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
