/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ua_org_antidotcb_dominus_engine_QuaternionNativeHelper */

#ifndef _Included_ua_org_antidotcb_dominus_engine_QuaternionNativeHelper
#define _Included_ua_org_antidotcb_dominus_engine_QuaternionNativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ua_org_antidotcb_dominus_engine_QuaternionNativeHelper
 * Method:    normalizeQuaternion
 * Signature: (Lua/org/antidotcb/dominus/engine/QuaternionNativeHelper/Quaternion;)I
 */
JNIEXPORT jint JNICALL Java_ua_org_antidotcb_dominus_engine_QuaternionNativeHelper_normalizeQuaternion
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
